baseURL: 'https://kraiwin.nl/'
languageCode: 'en-us'
title: Portfolio
theme: kraiwin_theme
params:
    name: Kraiwin Namsri
    contact:
        email: kraiwinrubian@gmail.com
        linkedin: https://www.linkedin.com/in/kraiwin/
        github: https://github.com/Kraiwin-Namsri/
    occupation: Student
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
        unsafe: true