name: Deploy Hugo Site to Internet Computer

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "website update"
  cancel-in-progress: true

jobs:
  deploy-ic:
    runs-on: ubuntu-latest
    environment:
      name: "Internet Computer Mainnet"
      url: ${{ steps.get-url.outputs.url }}
    env:
      HUGO_VERSION: 0.111.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules
        run: git submodule update --init

      - name: Install Hugo CLI
        run: |
          wget -O "${{ runner.temp }}/hugo.deb" "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb" \
          && sudo dpkg -i "${{ runner.temp }}/hugo.deb"

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo --baseURL "/"

      - name: Install DFX
        uses: dfinity/setup-dfx@main

      - name: Dump Identity
        run: |
          mkdir -p ~/.config/dfx/identity/default
          echo "$DFX_IDENTITY" | base64 -d > ~/.config/dfx/identity/default/identity.pem
          sed -i 's/\\r\\n/\r\n/g' ~/.config/dfx/identity/default/identity.pem
        env:
          DFX_IDENTITY: ${{ secrets.DFX_IDENTITY }}

      - name: Check Canister Balance
        run: |
          balance=$(dfx canister --network ic status portal 2>&1 >/dev/null | grep Balance: | sed 's/[^0-9]//g')
          LANG=en_US.UTF-8
          balance_formatted=$(echo $balance | awk '{printf "%'\''d\n", $0}')
          echo "Canister balance: $balance_formatted"

      - name: Deploy to Mainnet
        run: |
          export DFX_WARNING="-mainnet_plaintext_identity"
          dfx deploy --network=ic --no-wallet

      - name: Get URL
        id: get-url
        run: |
          URL="https://kraiwin.nl"
          echo "::set-output name=url::$URL"
