name: Deploy Hugo Site to Internet Computer

on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: "website update"
  cancel-in-progress: true

jobs:
  deploy-ic:
    runs-on: ubuntu-latest
    environment:
      name: "Internet Computer Mainnet"
      url: ${{ steps.get-url.outputs.url }}
    env:
      HUGO_VERSION: 0.111.3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules
        run: git submodule update --init

      - name: Install Hugo CLI
        run: |
          wget -O "${{ runner.temp }}/hugo.deb" "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb" \
          && sudo dpkg -i "${{ runner.temp }}/hugo.deb"

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo --minify --baseURL "/"

      - name: Install DFX
        uses: dfinity/setup-dfx@main

      - name: Dump Identity
        run: |
          mkdir -p ~/.config/dfx/identity/default
          echo "$DFX_IDENTITY_DESIGN_TEAM" | base64 -d > ~/.config/dfx/identity/default/identity.pem
          sed -i 's/\\r\\n/\r\n/g' ~/.config/dfx/identity/default/identity.pem
        env:
          DFX_IDENTITY_DESIGN_TEAM: ${{ secrets.DFX_IDENTITY_DESIGN_TEAM }}

      - name: Check Canister Balance
        run: |
          balance=$(dfx canister --network ic status portal 2>&1 >/dev/null | grep Balance: | sed 's/[^0-9]//g')
          LANG=en_US.UTF-8
          balance_formatted=$(echo $balance | awk '{printf "%'\''d\n", $0}')
          echo "Canister balance: $balance_formatted"
          if [ "5000000000000" -gt "$balance" ]; then
            canister_id=$(cat "$GITHUB_WORKSPACE/canister_ids.json" | jq -r '.portal.ic')
            template="{ \"channel\": \"C04EGHHU9U2\", \"blocks\": [ { \"type\": \"section\", \"text\": { \"type\": \"mrkdwn\", \"text\": \"@channel internetcomputer.org canister \`$canister_id\` balance is \`$balance_formatted\`.\n\nTop it up by\n- running \`dfx ledger --network ic top-up $canister_id --amount 5.0\`\n- or by adding the canister on the NNS and sending cycles to it.\" } } ]}"
            curl --data "$template" \
              -H "Content-type: application/json" \
              -H "Authorization: Bearer $SLACK_TOKEN" \
              -X POST https://slack.com/api/chat.postMessage \
              -o /dev/null
          fi
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

      - name: Deploy to Mainnet
        run: dfx deploy --network=ic --no-wallet portal

      - name: Get URL
        id: get-url
        run: |
          URL="https://$(cat "$GITHUB_WORKSPACE/canister_ids.json" | jq -r '.portal.ic').raw.ic0.app"
          echo "::set-output name=url::$URL"
